# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 5, 13, 18, 26, 156123, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
