# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 21:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_claim_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='report',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
