# Generated by Django 2.0 on 2017-12-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='no_claims',
            field=models.ManyToManyField(default=None, related_name='no_claim', to='polls.Claim'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yes_claims',
            field=models.ManyToManyField(default=None, related_name='yes_claim', to='polls.Claim'),
        ),
    ]
