# Generated by Django 2.0 on 2017-12-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20171212_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500)),
                ('evidence', models.TextField(max_length=500)),
                ('submitted_answer', models.NullBooleanField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Claim'),
        ),
    ]
